name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Set Secret Value
        run: echo "SECRET_VALUE=${{ secrets.SECRET_VALUE }}" >> $GITHUB_ENV

      - name: Replace Placeholder with Secret Value
        run: sed -i "s/{{SECRET_VALUE}}/${{ secrets.SECRET_VALUE }}/g" index.html

      - name: Get Latest Tag
        id: get_latest_tag
        run: echo "::set-output name=latest_tag::$(git describe --abbrev=0 --tags)"
       # run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)
        
      - name: Increment Tag
        id: increment_tag
        run: echo "::set-output name=incremented_tag::v$(node -e 'console.log(require("semver").inc(process.env.LATEST_TAG, "patch"))')"
        #run: echo ::set-output name=tag::$(python increment_tag.py ${{ steps.get_latest_tag.outputs.tag }})

      - name: Create Tag
        if: success()
        run: git tag -a ${{ steps.increment_tag.outputs.incremented_tag }} -m "Version ${{ steps.increment_tag.outputs.incremented_tag }}"

      - name: Push Tag
        if: success()
        run: git push origin ${{ steps.increment_tag.outputs.incremented_tag }}
      
     # - name: Generate Version Number
     #   run: echo "VERSION=$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FIELD_0A89AA200 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FIELD_0A89AA200 }}
          action: "close"
